In [1]:
import pandas as pd
import numpy as np
import math


In [15]:
data = pd.read_csv("../../data/datacrab.txt", header=0, sep=' ')
data.head(4)
cw = data.width
n = len(cw)
data.dtypes

input       int64
color       int64
spine       int64
width     float64
satell      int64
weight      int64
dtype: object

In [3]:
# Regla de Scott
As = 3.5*cw.std()*n**(-1/3)
kA = round(math.ceil(cw.max()-cw.min())/As,0)
print(kA)

#Amplitud de los intervalos
I_As = round((cw.max()-cw.min())/kA,2)    
print(I_As)

# Extremo delos intervalos
L1 = cw.min()- 1/2*0.1
print(L1)

L = L1 + I_As * np.arange(10)
print(L)

# Marcas de clase
X1 = round((L[0]+L[1])/2,2)
print(X1)
XA = X1 + I_As * np.arange(9)
print(XA)

10.0
1.25
20.95
[20.95 22.2  23.45 24.7  25.95 27.2  28.45 29.7  30.95 32.2 ]
21.58
[21.58 22.83 24.08 25.33 26.58 27.83 29.08 30.33 31.58]


## Regla de la raiz cuadrada

In [4]:
kR = round(math.ceil(math.sqrt(n)),0)
print(kR)

#Amplitud de los intervalos
I_R = round((cw.max()-cw.min())/kR,2)   
print(I_R)

# Extremo delos intervalos
L1R = round(cw.min()- 1/2*0.14,2)
print(L1R)

LR = L1R + I_R * np.arange(10)
print(LR)

# Marcas de clase
X1R = round((LR[0]+L[1])/2,2)
print(X1R)
XR = X1R + I_R * np.arange(9)
print(XR)

14
0.89
20.93
[20.93 21.82 22.71 23.6  24.49 25.38 26.27 27.16 28.05 28.94]
21.56
[21.56 22.45 23.34 24.23 25.12 26.01 26.9  27.79 28.68]


## Regla de Sturgest 

In [5]:
kSt = round(math.ceil(1+math.log(n,2)),0)
print(kSt)

#Amplitud de los intervalos
I_St = round((cw.max()-cw.min())/kSt,2)   
print(I_St)

# Extremo delos intervalos
L1St = round(cw.min()- 1/2*0.09,2)
print(L1St)

LSt = L1St + I_St * np.arange(10)
print(LSt)

# Marcas de clase
X1St = round((LSt[0]+L[1])/2,2)
print(X1St)
XSt = X1St + I_St * np.arange(9)
print(XSt)

9
1.39
20.95
[20.95 22.34 23.73 25.12 26.51 27.9  29.29 30.68 32.07 33.46]
21.58
[21.58 22.97 24.36 25.75 27.14 28.53 29.92 31.31 32.7 ]


## Regla de Freedman-Diaconisc

In [6]:
Afd = 2*(cw.quantile(0.75)-cw.quantile(0.25))*n**(-1/3)
kfd = round(math.ceil((cw.max()-cw.min())/(Afd)),2)
print(kfd)

print('Amplitud de los intervalos')
I_fd = round((cw.max()-cw.min())/kfd,2)   
print(I_fd)

print('Extremo delos intervalos')
L1fd = round(cw.min()- 1/2*0.13,2)
print(L1fd)

Lfd = L1fd + I_fd * np.arange(10)
print(Lfd)

print('Marcas de clase')
X1fd = round((Lfd[0]+L[1])/2,2)
print(X1fd)
Xfd = X1fd + I_St * np.arange(9)
print(Xfd)

13
Amplitud de los intervalos
0.96
Extremo delos intervalos
20.93
[20.93 21.89 22.85 23.81 24.77 25.73 26.69 27.65 28.61 29.57]
Marcas de clase
21.56
[21.56 22.95 24.34 25.73 27.12 28.51 29.9  31.29 32.68]
