## Matrices

In [10]:
row= [1,2,3]
col = [3,4,5]
M = [row, col]
M[1][2]

5

In [13]:
import numpy as np
M = np.array((col, row))
M

array([[3, 4, 5],
       [1, 2, 3]])

In [14]:
A= np.array([[2,5],[5,5]])
B= np.array([[4,5],[5,7]])

In [15]:
A + B

array([[ 6, 10],
       [10, 12]])

In [18]:
A.dot(B)

A.transpose()

A.trace()

7

In [23]:
np.linalg.matrix_rank(A)

np.linalg.matrix_power(A, 3)

np.linalg.det(B)

np.linalg.inv(B)

np.linalg.inv(B).dot(B)

array([[ 1.00000000e+00, -1.77635684e-15],
       [ 8.88178420e-16,  1.00000000e+00]])